name: 'Issue form parser'
description: 'Parses issues created by Issue Forms to JSON format"
author: 'onmax'
inputs:
  body:
    required: true
    description: 'the body of the issue'
runs:
  using: 'node16'
  main: 'dist/index.js'
