name: 'Issue form parser'
description: 'Parses issues created by Issue Forms to JSON format'
author: 'onmax'

branding:
  icon: 'clipboard'
  color: 'blue'

inputs:
  issue_number:
    required: true
    description: 'The issue number to parse'
  github_token:
    required: true
    description: 'The GitHub token to use for authentication and fetching the issue. Defaults to the `GITHUB_TOKEN` secret.'
    default: ${{ github.token }}
outputs:
  payload:
    description: 'The contents of the issue in a JSON format'
runs:
  using: 'node16'
  main: 'dist/index.js'
