name: Build
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  issues:
    types: [opened, reopened]

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
      - name: Checkouts
        uses: actions/checkout@v3
      - name: Run Action
        id: parse
        uses: ./
        with:
          issue_number: ${{ github.event.issue.number || 10 }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Show parsed payload
        run: |
          echo "${{ toJson(steps.parse.outputs.payload) }}"
